# fly.toml app configuration file generated for shy-river-4175 on 2023-05-30T08:03:50+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shy-river-4175"
primary_region = "lax"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
